server:
  port: 8080
  servlet:
    context-path: /joker

spring:
  application:
    name: joker
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB


# MinIO对象存储相关配置
minio:
  endpoint: http://123.56.142.9:9090 #MinIO服务所在地址
  bucket_name: joker #存储桶名称
  access_key: zhengdeqi #访问的key
  secret_key: zheng08184916 #访问的秘钥